### Notes

* Matrix multiplication is one of the most fundamental computer operations. It's been heavily optimized over the years.
* The naive algorithm taught as the definition of matrix multiplication is $\Theta(n^3)$.
* Strassen's method is $\Theta(n^{\log(7)})$, which is asymptotically faster. There's an even faster algorithm for extremely large arrays, though.
* A fast implementation of this method requires that no array copying take place. This is trivial in C or C++, but this is the default behavior in a Python `list` (and a JavaScript `Array`). This is the (well, a) reason that Python's `numpy` is configured to return slices instead of values. JavaScript's `math.js` is (probably?) similar in this respect.

### Python recursive square matrix multiplication implementation

In [12]:
import numpy as np

def square_matrix_multiply_recursive(a, b):
    a = np.array(a)
    b = np.array(b)
    num_rows = a.shape[0]
    if num_rows == 1:
        return a[0,0]*b[0,0]
    else:
        pivot = num_rows / 2
        c11 = square_matrix_multiply_recursive(a[:pivot, :pivot], b[:pivot, :pivot]) +\
              square_matrix_multiply_recursive(a[:pivot, pivot:], b[pivot:, :pivot])
        c12 = square_matrix_multiply_recursive(a[:pivot, :pivot], b[:pivot, pivot:]) +\
              square_matrix_multiply_recursive(a[:pivot, pivot:], b[pivot:, pivot:])
        c21 = square_matrix_multiply_recursive(a[pivot:, :pivot], b[:pivot, :pivot]) +\
              square_matrix_multiply_recursive(a[pivot:, pivot:], b[pivot:, :pivot])
        c22 = square_matrix_multiply_recursive(a[pivot:, :pivot], b[:pivot, pivot:]) +\
              square_matrix_multiply_recursive(a[pivot:, pivot:], b[pivot:, pivot:])
        return np.vstack([np.hstack([c11, c12]), np.hstack([c21, c22])])
#         return np.concatenate(np.array([[c11, c12], [c21, c22]]))

In [22]:
square_matrix_multiply_recursive([[1]], [[1]]) == np.matmul([[1]], [[1]])

array([[ True]], dtype=bool)

In [14]:
square_matrix_multiply_recursive([[0, 1],[1,2]], [[0, 1],[1,2]]) == np.matmul([[0, 1],[1,2]], [[0, 1],[1,2]])

C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:13: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:14: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


array([[ True,  True],
       [ True,  True]], dtype=bool)

In [21]:
square_matrix_multiply_recursive([[0,1,2,3],[1,2,3,4],[0,1,2,3],[1,2,3,4]], [[0,1,2,3],[1,2,3,4],[0,1,2,3],[1,2,3,4]]) ==\
    np.matmul([[0,1,2,3],[1,2,3,4],[0,1,2,3],[1,2,3,4]], [[0,1,2,3],[1,2,3,4],[0,1,2,3],[1,2,3,4]])

C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:13: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Alex\Anaconda3\envs\algos\lib\site-packages\ipykernel\__main__.py:14: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)